import path from 'path';
import { execGit, writeMarkdown, writeJson } from './utils.mjs';

const ROOT_DIR = process.cwd();

export function analyzeGit() {
  console.log('[AI Git Analyzer] Parsing Git topology and history...');

  const head = execGit('rev-parse HEAD', { fallback: 'UNKNOWN' });
  const shortHead = execGit('rev-parse --short HEAD', { fallback: 'UNKNOWN' });
  const branch = execGit('rev-parse --abbrev-ref HEAD', { fallback: 'main' });
  const status = execGit('status --porcelain', { fallback: '' });
  const isDirty = status.length > 0;

  const rawLog = execGit('log -n 30 --pretty=format:"%H|%h|%P|%an|%ad|%s" --date=iso', { fallback: '' });
  const commits = [];

  if (rawLog) {
    const lines = rawLog.split('\n');
    for (const line of lines) {
      if (!line.trim()) continue;
      const [sha, shortSha, parents, author, date, subject] = line.split('|');
      commits.push({
        sha,
        shortSha,
        parents: parents ? parents.split(' ') : [],
        author,
        date,
        subject,
      });
    }
  }

  const initialCommit = commits.length > 0 ? commits[commits.length - 1] : { sha: 'UNKNOWN', shortSha: 'UNKNOWN' };
  const latestCommit = commits.length > 0 ? commits[0] : { sha: 'UNKNOWN', shortSha: 'UNKNOWN' };

  // Save machine readable git index
  const gitIndex = {
    repository: 'Ankitkr-ak007/Portfolio',
    head,
    shortHead,
    branch,
    isDirty,
    initialCommit,
    latestCommit,
    commitCount: commits.length,
    commits,
    generatedAt: new Date().toISOString(),
  };

  writeJson(path.join(ROOT_DIR, '.ai/cache/git-index.json'), gitIndex);

  // Generate GIT_HISTORY.md
  let gitMd = `<!-- AUTO-GENERATED — DO NOT EDIT MANUALLY -->
<!-- Generated by: npm run ai:sync -->
<!-- Source: Git log & topology -->

# GIT HISTORY INTELLIGENCE

*Repository Origin, Current State, and Recent Commit Topology*

## 1. REPOSITORY SUMMARY
* **Branch**: \`${branch}\`
* **Current HEAD SHA**: \`${head}\` (\`${shortHead}\`)
* **Worktree Status**: \`${isDirty ? 'DIRTY (Uncommitted changes exist)' : 'CLEAN'}\`
* **Initial Commit SHA**: \`${initialCommit.shortSha}\`
* **Indexed Commits**: ${commits.length}

## 2. RECENT COMMIT TIMELINE (TOP 30)

| Short SHA | Date | Author | Commit Message |
| :--- | :--- | :--- | :--- |
`;

  for (const c of commits) {
    gitMd += `| \`${c.shortSha}\` | ${c.date ? c.date.split(' ')[0] : 'N/A'} | ${c.author} | ${c.subject} |\n`;
  }

  gitMd += `
## 3. BRANCH TOPOLOGY MAP
\`\`\`text
${initialCommit.shortSha} (Initial Commit)
  ↓
  [... Development History ...]
  ↓
${latestCommit.shortSha} (${latestCommit.subject}) [HEAD -> ${branch}]
\`\`\`

*For full commit patch diffs, execute: \`git show <SHA>\`*
`;

  writeMarkdown(path.join(ROOT_DIR, 'docs/ai/GIT_HISTORY.md'), gitMd);
  console.log('[AI Git Analyzer] Git history indexed successfully.');
}

if (process.argv[1] && process.argv[1].endsWith('analyze-git.mjs')) {
  analyzeGit();
}
