import path from 'path';
import fs from 'fs';
import { scanDirectory, writeMarkdown } from './utils.mjs';

const ROOT_DIR = process.cwd();

export function detectGaps() {
  console.log('[AI Gap Detector] Scanning for TODOs, FIXMEs, and context drift...');

  const files = scanDirectory(ROOT_DIR, ['node_modules', '.git', 'dist', 'build', '.ai/cache', 'docs/ai']);
  const todos = [];

  for (const f of files) {
    if (!f.path.endsWith('.ts') && !f.path.endsWith('.tsx') && !f.path.endsWith('.js') && !f.path.endsWith('.json') && !f.path.endsWith('.css')) continue;

    const fullPath = path.join(ROOT_DIR, f.path);
    try {
      const content = fs.readFileSync(fullPath, 'utf-8');
      const lines = content.split('\n');
      lines.forEach((line, index) => {
        if (line.match(/(TODO|FIXME|HACK|XXX|TEMP|PLACEHOLDER)/i)) {
          const match = line.match(/(TODO|FIXME|HACK|XXX|TEMP|PLACEHOLDER)/i)[0].toUpperCase();
          todos.push({
            file: f.path,
            line: index + 1,
            type: match,
            text: line.trim(),
          });
        }
      });
    } catch {
      // Ignore binary or unreadable
    }
  }

  // Check context drift
  const missingDocs = [];
  const requiredAiDocs = [
    'PROJECT_CONTEXT.md',
    'PROJECT_STATE.md',
    'ARCHITECTURE.md',
    'DESIGN_SYSTEM.md',
    'ENGINEERING_RULES.md',
    'DECISIONS.md',
    'CURRENT_WORK.md',
    'KNOWN_ISSUES.md',
    'CHANGELOG.md',
    'GIT_HISTORY.md',
    'FILE_MAP.md',
    'DEPENDENCIES.md',
    'ROUTES.md',
    'ASSETS.md',
    'ENVIRONMENT.md',
    'TESTING.md',
    'PERFORMANCE.md',
    'AI_GAP_REPORT.md',
    'SESSION_LOG.md',
  ];

  for (const doc of requiredAiDocs) {
    if (!fs.existsSync(path.join(ROOT_DIR, 'docs/ai', doc))) {
      missingDocs.push(doc);
    }
  }

  let gapMd = `<!-- AUTO-GENERATED — DO NOT EDIT MANUALLY -->
<!-- Generated by: npm run ai:sync -->

# AI GAP REPORT & CONTEXT DRIFT AUDIT

*Architectural Gaps, Context Drift, and In-Code TODOs*

## 1. CONTEXT INTEGRITY & DRIFT
* **Missing Documentation**: ${missingDocs.length > 0 ? missingDocs.join(', ') : 'None (All 19 AI docs present)'}
* **Documentation Drift Status**: ${missingDocs.length === 0 ? 'HEALTHY — All core knowledge documents verified' : 'ATTENTION — Missing docs detected'}

## 2. CODEBASE TODO / FIXME AUDIT (${todos.length} Detected)

| Severity | Type | File Location | Snippet / Context |
| :--- | :--- | :--- | :--- |
`;

  if (todos.length === 0) {
    gapMd += `| INFO | CLEAN | Codebase | No unresolved TODO/FIXME markers found in production code |\n`;
  } else {
    for (const t of todos) {
      gapMd += `| INFO | ${t.type} | \`${t.file}:${t.line}\` | \`${t.text.replace(/\|/g, '\\|')}\` |\n`;
    }
  }

  gapMd += `
## 3. RECOMMENDED IMPROVEMENTS
1. **[RECOMMENDED]** E2E Route smoke test for WebGL fallback verification.
2. **[RECOMMENDED]** Lighthouse desktop/mobile score audit on production build.
3. **[INFO]** Keep \`SESSION_LOG.md\` updated after every developer AI session.
`;

  writeMarkdown(path.join(ROOT_DIR, 'docs/ai/AI_GAP_REPORT.md'), gapMd);
  console.log(`[AI Gap Detector] Gap report generated with ${todos.length} TODO(s) identified.`);
}

if (process.argv[1] && process.argv[1].endsWith('detect-gaps.mjs')) {
  detectGaps();
}
