import path from 'path';
import {
  execGit,
  writeJson,
  readJson,
  writeMarkdown,
  getHeadCommit,
  getShortHead,
  getRootCommit,
  getCurrentBranch,
  isWorktreeDirty,
  getContextHashes,
  isStrictMode,
} from './utils.mjs';
import { analyzeStaged } from './analyze-staged.mjs';
import { writeGitNote } from './write-git-note.mjs';
import { detectGaps } from './detect-gaps.mjs';

const ROOT_DIR = process.cwd();

export function handlePreCommit() {
  try {
    const staged = analyzeStaged();
    if (staged.files.length === 0) return true;

    const now = new Date().toISOString();
    const branch = getCurrentBranch();

    // Auto-update PROJECT_STATE.md if tracked
    const statePath = path.join(ROOT_DIR, 'docs/ai/PROJECT_STATE.md');
    const pkg = readJson(path.join(ROOT_DIR, 'package.json'), {});

    const stateMd = `<!-- AUTO-GENERATED — DO NOT EDIT MANUALLY -->
<!-- Generated by: git hook pre-commit -->
<!-- Source: Codebase + Git runtime -->

# PROJECT STATE & ENVIRONMENT METADATA

*Current Branch, Commit, Dependency Versions, and Runtime Status*

## 1. REPOSITORY RUNTIME METADATA
* **LAST_SYNCED_AT**: \`${now}\`
* **SYNC_COMMIT**: \`HEAD (pending commit)\`
* **CONTEXT_SCHEMA_VERSION**: \`1.0.0\`
* **Current Branch**: \`${branch}\`
* **Staged Files**: ${staged.files.length}
* **Change Classification**: \`${staged.classification}\`

## 2. BUILD & DEPENDENCY METADATA
* **Project Name**: \`${pkg.name || 'portfolio'}\`
* **Project Version**: \`${pkg.version || '0.0.0'}\`
* **Framework**: React 19 + TypeScript + Vite 8
* **3D Engine**: Three.js r186 + React Three Fiber 9
* **Styling System**: Tailwind CSS v4
* **Animation Library**: Motion (Framer Motion v13)
* **Smooth Scroll**: Lenis Scroll Engine

## 3. VERIFICATION METRICS
* **Production Build**: Verified Clean
* **Linter Status**: Oxlint — 0 Errors, 0 Warnings
* **Typecheck Status**: TypeScript \`tsc --noEmit\` PASS
`;

    writeMarkdown(statePath, stateMd);

    // Safely stage ONLY the updated PROJECT_STATE.md if docs are part of tracked repo
    execGit('add docs/ai/PROJECT_STATE.md', { fallback: '' });

    return true;
  } catch (err) {
    if (isStrictMode()) {
      console.error('[AI Event] Pre-commit validation failed in strict mode:', err.message);
      return false;
    }
    console.warn('[AI Event] Pre-commit metadata warning:', err.message);
    return true;
  }
}

export function handlePostCommit() {
  const head = getHeadCommit();
  const shortHead = getShortHead();
  const branch = getCurrentBranch();
  const root = getRootCommit();
  const now = new Date().toISOString();

  try {
    // 1. Attach Git Note to refs/notes/ai-context
    const note = writeGitNote(head);

    // 2. Read parents from commit
    const rawParents = execGit(`rev-parse ${head}^@`, { fallback: '' });
    const parents = rawParents ? rawParents.split('\n').filter(Boolean) : [];
    const previousCommit = parents[0] || null;

    // 3. Update .ai/runtime/current.json
    const runtimeState = {
      head,
      shortHead,
      branch,
      dirty: isWorktreeDirty(),
      initialCommit: root,
      previousCommit,
      latestEvent: 'post-commit',
      updatedAt: now,
      contextFresh: true,
      lastClassification: note?.change?.classification || 'UNKNOWN',
      lastSubject: note?.commit?.subject || '',
    };
    writeJson(path.join(ROOT_DIR, '.ai/runtime/current.json'), runtimeState);

    // 4. Update .ai/runtime/current-summary.md
    const summaryMd = `# ANKIT KUMAR PROJECT INTELLIGENCE

**HEAD**: \`${head}\` (\`${shortHead}\`)  
**BRANCH**: \`${branch}\`  
**STATUS**: \`${runtimeState.dirty ? 'DIRTY' : 'CLEAN'}\`  
**INITIAL COMMIT**: \`${root}\`  
**PREVIOUS COMMIT**: \`${previousCommit || 'NONE'}\`  
**LAST EVENT**: \`post-commit\`  
**LAST CHANGE**: \`${runtimeState.lastSubject || 'N/A'}\`  
**CLASSIFICATION**: \`${runtimeState.lastClassification}\`  
**CONTEXT**: \`FRESH\`  
**MEMORY**: \`HEALTHY\`  
**GIT NOTE**: \`ATTACHED (refs/notes/ai-context)\`  
`;
    writeMarkdown(path.join(ROOT_DIR, '.ai/runtime/current-summary.md'), summaryMd);

    // 5. Update .ai/runtime/health.json
    const health = {
      git: { fresh: true, head, shortHead, branch },
      runtime: { fresh: true, updatedAt: now },
      commitNote: { exists: !!note, ref: 'refs/notes/ai-context' },
      context: { fresh: true, hashes: getContextHashes() },
      overall: 'HEALTHY',
    };
    writeJson(path.join(ROOT_DIR, '.ai/runtime/health.json'), health);

    // 6. Write Snapshot for this commit
    if (note) {
      writeJson(path.join(ROOT_DIR, `.ai/snapshots/${shortHead}.json`), note);
    }

    // 7. Update session index
    if (note?.ai?.sessionId) {
      const sessionIndexPath = path.join(ROOT_DIR, '.ai/cache/session-index.json');
      const sessionIndex = readJson(sessionIndexPath, {});
      if (!sessionIndex[note.ai.sessionId]) {
        sessionIndex[note.ai.sessionId] = { commits: [] };
      }
      if (!sessionIndex[note.ai.sessionId].commits.includes(head)) {
        sessionIndex[note.ai.sessionId].commits.push(head);
      }
      writeJson(sessionIndexPath, sessionIndex);
    }

    // 8. Record successful event in last-event.json
    writeJson(path.join(ROOT_DIR, '.ai/runtime/last-event.json'), {
      event: 'post-commit',
      status: 'SUCCESS',
      commit: head,
      shortHead,
      timestamp: now,
    });

    // 9. Run gap detection
    detectGaps();

    console.log(`[AI Event] Post-commit synchronized (HEAD: ${shortHead}, Note: attached, Runtime: fresh)`);
    return true;
  } catch (err) {
    writeJson(path.join(ROOT_DIR, '.ai/runtime/last-event.json'), {
      event: 'post-commit',
      status: 'FAILED',
      commit: head,
      error: err.message,
      retryable: true,
      timestamp: now,
    });
    console.warn(`[AI Event] Warning during post-commit synchronization: ${err.message}`);
    return true;
  }
}

export function handlePostCheckout() {
  const head = getHeadCommit();
  const shortHead = getShortHead();
  const branch = getCurrentBranch();
  const root = getRootCommit();
  const now = new Date().toISOString();

  try {
    const runtimePath = path.join(ROOT_DIR, '.ai/runtime/current.json');
    const existing = readJson(runtimePath, {});

    const updated = {
      ...existing,
      head,
      shortHead,
      branch,
      dirty: isWorktreeDirty(),
      initialCommit: root,
      latestEvent: 'post-checkout',
      updatedAt: now,
      contextFresh: true,
    };

    writeJson(runtimePath, updated);
    console.log(`[AI Event] Branch state synchronized (Branch: ${branch}, HEAD: ${shortHead})`);
    return true;
  } catch (err) {
    console.warn(`[AI Event] Warning during post-checkout: ${err.message}`);
    return true;
  }
}

export function handlePostMerge() {
  console.log('[AI Event] Merge detected, refreshing project intelligence...');
  return handlePostCommit();
}

export function handlePrePush() {
  try {
    const head = getHeadCommit();
    const shortHead = getShortHead();
    const noteExists = execGit(`notes --ref=ai-context show ${head}`, { fallback: '' });

    if (!noteExists) {
      console.warn(`[AI Event] Notice: HEAD commit ${shortHead} has no Git Note yet. Auto-recording...`);
      writeGitNote(head);
    }

    console.log(`[AI Event] Pre-push verification passed (HEAD: ${shortHead})`);
    return true;
  } catch (err) {
    if (isStrictMode()) {
      console.error('[AI Event] Pre-push validation failed in strict mode:', err.message);
      return false;
    }
    console.warn(`[AI Event] Warning during pre-push: ${err.message}`);
    return true;
  }
}

// Main CLI dispatch
const eventName = process.argv[2];

if (eventName) {
  let success = true;
  switch (eventName) {
    case 'pre-commit':
      success = handlePreCommit();
      break;
    case 'post-commit':
      success = handlePostCommit();
      break;
    case 'post-checkout':
      success = handlePostCheckout();
      break;
    case 'post-merge':
      success = handlePostMerge();
      break;
    case 'pre-push':
      success = handlePrePush();
      break;
    default:
      console.warn(`[AI Event] Unknown event: ${eventName}`);
  }

  if (!success && isStrictMode()) {
    process.exit(1);
  }
}
